# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=32)),
                ('module_name', models.CharField(max_length=32)),
                ('column', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together=set([('app_label', 'module_name', 'column', 'value', 'object_id')]),
        ),
    ]
